language: node_js
node_js:
- '8'
branches:
  only:
  - master
  - develop
  - "/^v.*$/"
before_script:
- npm install
before_deploy:
- npm run prerelease
deploy:
  - provider: npm
    skip_cleanup: true
    email: pkerpedjiev@gmail.com
    api_key:
      secure: bGXT7Z49yzjafFVO2tmYq5szSKqXcA+8CBp7Z49HambRNXqX8HeSzmazuRfFM722srr7T/3kwBC57mZni1KQ4/bwjLbQ2uIAWwSXafPNpCHKxULimBQNb6UBTmJMHcPnIT/1SCkoH29ZhVmpSYb/RaEOboudHV762g/353e+J6BAN6Q5FCNkNVMyj0yYIJ9D0GUzISKXgC0X6ofAThIXS7eV8llf6C0pRqmYmZpjHDSz3/K8/oS/ph/DToyB2lB+cEw7aJ3cu8Iko87VuQu2cSbDwXyx32KOY3K4UrClbARuyHOeQ+6FDs4DI1/4VLujP4JOlQKl/XjTP70JU6FG4f7IaZP0J4jjL/R1ue1HhvEJWIf70QAjSdGjcwmJDHvB9Yqas+JZRO721XcBkrCU9Ns/57a0z+5KADot62sczVBU3CRfvasFyA2QuJ04c7sFwgHAQ5Jbi2GB0bqA184s5VyD77lfW59fh/fqsThlqhUHCUGtliXDJ+UN9lmoF9oLXrq+msn67EFBaxQE6EdLEEtSjs1t22k/03/ozt1MXkVcK7JmhO0MrPcCBpRUwxS7mkvu+Hn1rvbQAVC8KVxRCzWtkHNspP3HbIj/OMLKyZkfz7e6H+YwPJI5xYD6EQKIXl+FoAuhOC/PeqP5O/PsSkkQ1A18tscLOgfQ9vG4j+c=
    on:
      tags: true
      repo: higlass/higlass-pileup
      branch: master
  - provider: releases
    skip_cleanup: true
    email: pkerpedjiev@gmail.com
    api_key:
      secure: py7B8Gfn3GevdtRGRQQE0kN1DC4Ug8smNGrctiVHV/zK2znASJMXsi00kdrnUX+VSAdyEqmZ6Q7NMCIrVe6wazbePDZrzD0yVMoCaWQUz37F42ia110Cgb8rGdFiY48lfr12AZwJduq9r019yKajtKhD/FAxfmgTMzvCU2XbQf+jp4YOnA52yWSFUWjH9+3urPNKmGLapXO2ypaR7Fk9pCgvpl1dIPrLBCWb4Cb5u4P54VRQQgd0HWT1xs5TOAyAZFuhAg53dz8FPP7roPASjZ2nCc3eGyNeIbldJEf6KEjqlIo2gLXaEZ+VDZFqm+Z903DVCU82qJ/fZGnFjejni5ryS4yDkSHfZX44hYf7S1fm2NpX+si0StzlDYOggVC2HjUczKV0DrjNDu9EgVijKINikJa+fhx/EmFCgQveyeTqjLNRu27k98OXPwRIW9dqrMZiH3ANwKVWzngoirz8dYMQDXKkKDbnsoCsrpXQd8BbnO6hfLtjKOKUZ7j4ZWTChHCYc7QiZJQoBya33lD4KbJI6OuMmLaQY4r3W1X81DdKeoThcNqUt7WfWZIEWBKjLG5INImTBO8ozWXElwIHVYjzlCj+uKlOKOL6po33ijnTKXz5Rhn5D8mZgVNMffh44uS0/XDdoyaPyFFruP5Ce7vp1uHzSZjlUBfapNmMj0A=
    file: dist.zip
    on:
      repo: higlass/higlass-pileup
