language: node_js
node_js:
- '8'
branches:
  only:
  - master
  - develop
  - "/^v.*$/"
before_script:
- npm install
before_deploy:
- npm run prerelease
deploy:
  - provider: npm
    skip_cleanup: true
    email: pkerpedjiev@gmail.com
    api_key:
      secure: 6tJbpf/r+5g99AESuiPR/GkhaWG6wGT9GTH27NzLIWH3bbeg+TUJOc5I/B9IvufUWoK93JKGPPv4xS5hR7LEMANzbyD3KxY0Gd3OkO+gDRfTt2fQkyhtaH+fPWoZ7ilnQJ4tNcHm3oboKFQIIXFdfIh7RFSn0TkvK9qbguip7w22w1mxtlnsokdnmcq+NhwnMWbtF0eqQnbBry1dYUp/TRxfXW6mNnlP3+/M1wRUO97lV/MJnY1TBatfYb9pJ9nckK5/aAsfkdKKf1X3f2+Eyz+CuTvGaXWQYLi8Rl3ehk2RLEdWDoaNgfVKfAN4nnZaKhJ8OSijM5TTDMe5UUDA6Y5kcWT13ZOVlWTWmD8d5cyul1prolRRn25vS30FbHv8Ei4YoIFwQun5FRq2mExVgO+kEWIlU+mvnbtrU4fjPnO0GVz427s+by3eGkNGQHoi8dGF8E/AIiMgat5qFRfJPgoSqRHyYDxs3Mcq/5F1XWgBpBCP82j0O8oG2Jq9kubGmuijZ/xc7FOi5wjug3XpTaXYBmYqecM1Mnqw+S3CQMz9Kfdelyzxck1k6CbwlIaqxaFimVGdwbbXKemxjn/rKUSoEfdZTgNB1bSpJ8OqRrwqmNkVfROF2EMtKQ4VmnHVnetPtNWV6apvMW4tWiqWTIu42pgJq7ZxjP5l4rMIPVk=
    on:
      tags: true
      repo: higlass/higlass-pileup
      branch: master
  - provider: releases
    skip_cleanup: true
    email: pkerpedjiev@gmail.com
    api_key:
      secure: py7B8Gfn3GevdtRGRQQE0kN1DC4Ug8smNGrctiVHV/zK2znASJMXsi00kdrnUX+VSAdyEqmZ6Q7NMCIrVe6wazbePDZrzD0yVMoCaWQUz37F42ia110Cgb8rGdFiY48lfr12AZwJduq9r019yKajtKhD/FAxfmgTMzvCU2XbQf+jp4YOnA52yWSFUWjH9+3urPNKmGLapXO2ypaR7Fk9pCgvpl1dIPrLBCWb4Cb5u4P54VRQQgd0HWT1xs5TOAyAZFuhAg53dz8FPP7roPASjZ2nCc3eGyNeIbldJEf6KEjqlIo2gLXaEZ+VDZFqm+Z903DVCU82qJ/fZGnFjejni5ryS4yDkSHfZX44hYf7S1fm2NpX+si0StzlDYOggVC2HjUczKV0DrjNDu9EgVijKINikJa+fhx/EmFCgQveyeTqjLNRu27k98OXPwRIW9dqrMZiH3ANwKVWzngoirz8dYMQDXKkKDbnsoCsrpXQd8BbnO6hfLtjKOKUZ7j4ZWTChHCYc7QiZJQoBya33lD4KbJI6OuMmLaQY4r3W1X81DdKeoThcNqUt7WfWZIEWBKjLG5INImTBO8ozWXElwIHVYjzlCj+uKlOKOL6po33ijnTKXz5Rhn5D8mZgVNMffh44uS0/XDdoyaPyFFruP5Ce7vp1uHzSZjlUBfapNmMj0A=
    file: dist.zip
    on:
      repo: higlass/higlass-pileup
