language: node_js
node_js:
- '8'
branches:
  only:
  - master
  - develop
  - "/^v.*$/"
before_script:
- npm install
before_deploy:
- npm run prerelease
deploy:
  - provider: npm
    skip_cleanup: true
    email: pkerpedjiev@gmail.com
    api_key:
      secure: C7fYJsE00wulwb3KEJfk3XeBVR+9rbToJOqbctZgnK5ns6pAu9e7sJnqKUQG1bY4iTKcHNPI3MMmse5+xjr1pBXQ6KPqcacXcJTLbGppib1/SiJftJ/lHZwVxtGREoVon+9K54uPScTNfPkXEuf+gLXluoQgwyB4WwQHwkk+ImMYVwUlvz6/Lo9ExQvQ6ULPpsI6N4Wx03WdUi+gTFpgfJiMb2fQi4for5KbxCAove7vgHqSC4ENKDWwzT3R1M9vU0eaf0z8lYa0aC80abUhWXVbcf0p6s9bLpQ+u78l+sWTUPpUqfXOQtL0tYBA5p7owY9PZID8vXTgEr0EQ8gtFsg4QSMgqnGnaq9r0CGRsN6OBpDKPG/4KKz2XAvG42/qCcvVy9QV41lfN6IPhDdKDnMi2bpfcnHGuug639FuMqOI9UROFNjrrIrvaEtrX1YVPyU5EqawA/O16skyNocYx0Ho/9x47b+JIhseBdq2W5Y1lASDJiPXcBc6MAqWcwGz/veSTFcSxN3a70nC7qnIC12gr0nj0UOnvGyvPm2RjYYa4KOlvU8QNmeJ+88k01JngQQpPYAilr1zJH+rM9A0Ix4I1dAePJ4r3P/IEs0xuJVV1xfElqf3/WakLddvinPA9pQFgKXVYaKOJshm6AoUDznQfxJmHkjD3YILMW8q0E8=
    on:
      tags: true
      repo: higlass/higlass-pileup
      branch: master
  - provider: releases
    skip_cleanup: true
    email: pkerpedjiev@gmail.com
    api_key:
      secure: py7B8Gfn3GevdtRGRQQE0kN1DC4Ug8smNGrctiVHV/zK2znASJMXsi00kdrnUX+VSAdyEqmZ6Q7NMCIrVe6wazbePDZrzD0yVMoCaWQUz37F42ia110Cgb8rGdFiY48lfr12AZwJduq9r019yKajtKhD/FAxfmgTMzvCU2XbQf+jp4YOnA52yWSFUWjH9+3urPNKmGLapXO2ypaR7Fk9pCgvpl1dIPrLBCWb4Cb5u4P54VRQQgd0HWT1xs5TOAyAZFuhAg53dz8FPP7roPASjZ2nCc3eGyNeIbldJEf6KEjqlIo2gLXaEZ+VDZFqm+Z903DVCU82qJ/fZGnFjejni5ryS4yDkSHfZX44hYf7S1fm2NpX+si0StzlDYOggVC2HjUczKV0DrjNDu9EgVijKINikJa+fhx/EmFCgQveyeTqjLNRu27k98OXPwRIW9dqrMZiH3ANwKVWzngoirz8dYMQDXKkKDbnsoCsrpXQd8BbnO6hfLtjKOKUZ7j4ZWTChHCYc7QiZJQoBya33lD4KbJI6OuMmLaQY4r3W1X81DdKeoThcNqUt7WfWZIEWBKjLG5INImTBO8ozWXElwIHVYjzlCj+uKlOKOL6po33ijnTKXz5Rhn5D8mZgVNMffh44uS0/XDdoyaPyFFruP5Ce7vp1uHzSZjlUBfapNmMj0A=
    file: dist.zip
    on:
      repo: higlass/higlass-pileup
